#!/bin/sh

# This will generate a password consisting of a non-trivial, a hyphen, and a random number between 100 and 900.
# For example, “dingledangl-149”
perl -e 'open IN, "</usr/share/dict/words";rand($.) < 1 && ($n=$_) while <IN>; $rand = int(rand(900) + 100);$password = substr($n,0,-2) . "-" . $rand . "\n";printf $password'
